# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Tom McGee
tagline:          Blogging like a boss
url:              http://tomcmcgee.com
paginate:         1
baseurl:          /
author:
  name:           Tom McGee
  url:            
  email:          tmmcgee13@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/tcmcgee
